#!/bin/bash

echo "Cloning repos..."
/snopsboot/cloneGitRepos.sh
/snopsboot/cacheGitCredentials.sh

rm -f /usr/bin/vi
ln -s /usr/bin/vim /usr/bin/vi

chown -Rf snops:snops /home/snops

echo ""
echo ""
echo "Personalizing the container from host volume (if exists)..."
echo ""
mkdir -p /var/jenkins_home/.ssh && cp -r /home/snops/host_volume/sshkeys/* /var/jenkins_home/.ssh >> /home/snops/log/cloneGitRepos.log 2>&1 || echo "no ssh keys were found in /home/snops/host_volume/sshkeys/"
mkdir -p /var/jenkins_home/.aws && cp /home/snops/host_volume/aws/credentials /var/jenkins_home/.aws/credentials >> /home/snops/log/cloneGitRepos.log 2>&1 || echo "no aws credentials were found in /home/snops/host_volume/aws/credentials"
mkdir -p /var/jenkins_home/.azure && cp /home/snops/host_volume/azure/credentials /var/jenkins_home/.azure/credentials >> /home/snops/log/cloneGitRepos.log 2>&1 || echo "no azure credentials were found in /home/snops/host_volume/azure/credentials"
chown -R jenkins:snops /var/jenkins_home/.ssh && chmod 600 /var/jenkins_home/.ssh/* >> /home/snops/log/cloneGitRepos.log 2>&1 || echo "problem changing permissions for /var/jenkins_home/.ssh/*"
ansible-playbook /home/snops/f5-rs-jenkins/playbooks/jenkins_config.yaml || echo "problem running jenkins setup playbook"


echo ""
echo ""
echo ""
echo ""

cat /etc/motd

echo ""
echo "(you can now detach by using Ctrl+P+Q)"
echo ""

/bin/bash --login
